# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-20 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='group',
            new_name='myGroup',
        ),
    ]
